"""Add is_selected to cart_items

Revision ID: add_is_selected_001
Revises: add_stock_reduction_001
Create Date: 2026-03-23 16:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_is_selected_001'
down_revision = 'add_stock_reduction_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('is_selected', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'is_selected')
    # ### end Alembic commands ###
