"""Add delivery proof fields to orders table

Revision ID: add_delivery_proof_001
Revises: add_delivery_date_time_001
Create Date: 2026-03-29 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_delivery_proof_001'
down_revision = 'add_delivery_date_time_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_proof', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('delivery_proof_public_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('delivery_proof_url', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('delivery_proof_2', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('delivery_proof_2_public_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('delivery_proof_2_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_proof_2_url')
    op.drop_column('orders', 'delivery_proof_2_public_id')
    op.drop_column('orders', 'delivery_proof_2')
    op.drop_column('orders', 'delivery_proof_url')
    op.drop_column('orders', 'delivery_proof_public_id')
    op.drop_column('orders', 'delivery_proof')
    # ### end Alembic commands ###
