"""Add requested delivery date and time to orders

Revision ID: add_delivery_date_time_001
Revises: add_is_selected_001
Create Date: 2026-03-25 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_delivery_date_time_001'
down_revision = 'add_is_selected_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('requested_delivery_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('requested_delivery_time', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'requested_delivery_time')
    op.drop_column('orders', 'requested_delivery_date')
    # ### end Alembic commands ###
